---
title: "L1 - TD Méthodologie expérimentale"
subtitle: ""
format: 
  revealjs: 
    chalkboard: true
    multiplex: true
    slide-number: 'c'  
    number-sections: false
    incremental: false
    theme: ["custom.scss"]
    
    
editor: visual
---

# Introduction 

Présentation et thèmes de recherche

Inscription sur l'espace de cours du groupe de TD 

Évaluation du TD

Organisation concrète du travail en TD

Prise de notes, répétition et mémorisation


# Séance 1

Objectifs

Être capable de :

- faire une recherche bibliographique sur des bases de données

- construire une bibliographie aux normes APA 7

## Faire une recherche bibliographique

- Dans des bases de données **scientifiques**
- À partir des ressources de la BU
- Définir et utiliser des mots-clefs (booléens)
- Normes APA 7 
- Un gestionnaire de bibliographie : Zotero 

# Séance 2 

Objectifs

Être capable de : 

- différencier des ressources bibliographiques en fonction de leur nature (types d’articles)
- dégager la structure d’un article expérimental et la mémoriser

## Nature et structure des articles scientifiques 

- Classer les articles proposés sur l'espace de cours en fonction de leur nature

  - Décrire et nommer chaque catégorie
  - Quels sont les points communs et les différences entre les catégories trouvées ? 
  
- Rechercher une sélection d'articles sur un thème au choix et les classer en fonction de leur nature

- Dégager la structure des articles expérimentaux

  - La noter et rédiger une description succincte de chaque partie

::: notes
sélection d'articles avec article expérimental, revue de littérature, commentaire ou réponse à un article, article méthodologique, article théorique, article d'opinion
:::


